### ISSUE TITLE
Hi Guys

### ISSUE THREAD

**Issue by medarke** [UPS-API/UPS-SDKs#1]
# Hello World.
Hey guys,

I am looking for a SDK so I can get prices from UPS. 
Based in the UK.
All I want is to get a price for delivery from point A to Point B.

Who can I speak to at UPS. - Hello world anyone seen this?

**Comment by UPSMichael** [comment]
Hi medarke, thank you for reaching out to us. Unfortunately, we do not currently offer any SDK to get prices from UPS. This can be done by navigating to [ups.com](https://www.ups.com/) and then using the Quote tab. Additionally, the [UPS Developer Portal(https://developer.ups.com/) has a catalog of APIs that you might find useful. For example, you could use the Rating API to shop for a shipment.
