### ISSUE TITLE
Unable to install Python Wheel File

### ISSUE THREAD

**Issue by pauljohnj** [UPS-API/UPS-SDKs#2]
# Issue Report Template for OAuth SDK

## Issue Summary
Please provide a brief summary of the issue you're encountering.

## Steps to Reproduce
Installing the Python client credential wheel file via "pip install" command.

## Error Code/Message
ERROR: ups_oauth_client_credential_sdk-1.0.whl is not a valid wheel filename.

## Environment
python version 3.12 & 3.13
-sdk v1.0

## Additional Information
Include any other relevant details that might help diagnose the issue..

If the issue persists or if you need immediate assistance, please email our support team at UPSOauthSDKsupport@ups.com with the details provided above.

Thank you for using OAuth SDK!

**Comment by UPSMichael** [comment]
Hi, thank you for reaching out. This SDK is not available in the Python Package Index, or other repositories. Please ensure you have downloaded the .whl file and point your installation to the correct directory.

**Comment by pauljohnj** [comment]
Hi there.

I'm using the command "pip install ups_oauth_client_credential_sdk-1.0.whl" in the directory where the .whl file exists and I am getting an error there. See image below: 

![image](https://github.com/user-attachments/assets/6b77cbd3-cfe0-48f5-95a9-43c08798b7a1)

Is there a mistake in the install command? 
Thank you!

**Comment by UPSMichael** [comment]
Can you try using the path to the file instead of just the file name? From your screenshot, this would look like `pip install D:/Job Stuff/Venus/UPS/ups_oauth_client_credential_sdk-1.0.whl`

**Comment by pauljohnj** [comment]
I tried just now.
![image](https://github.com/user-attachments/assets/64ac7844-c834-4948-98c4-5595373947cb)

It looked like the space was an issue so I retried with quotes but it unfortunately still gave the same error.

**Comment by UPSMichael** [comment]
Marking as closed.

**Comment by HarrisonAlmeida** [comment]
Hey there, I'm having the same issue installing the SDK. Tried the solutions above:
1. `pip install /home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk` -> removing the `-1.0.whl`
but I get 
```
ERROR: Invalid requirement: '/home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk'
Hint: It looks like a path. File '/home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk' does not exist. 
```

OS: Linux Ubuntu 
Pip version: 22.1
setuptools version: 65.5.0

**Comment by UPSMichael** [comment]
> Hey there, I'm having the same issue installing the SDK. Tried the solutions above:
> 
>     1. `pip install /home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk` -> removing the `-1.0.whl`
>        but I get
> 
> 
> ```
> ERROR: Invalid requirement: '/home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk'
> Hint: It looks like a path. File '/home/harrison-almeida/Documents/service/repo/ups_oauth_client_credential_sdk' does not exist. 
> ```
> 
> OS: Linux Ubuntu Pip version: 22.1 setuptools version: 65.5.0

Can you verify your path is correct? If you're using a virtual environment, the path might be different. The command looks correct otherwise.

**Comment by HarrisonAlmeida** [comment]
I'm not using a virtual env. Is there an expectation to upload the package to a repository, like pypi, any time soon?

**Comment by UPSMichael** [comment]
At this time there is no plan to migrate any packages to other repositories.

**Comment by daniel-gomes** [comment]
I'm having the same problem:
```
$ ls -lah ~/Downloads/ups_oauth_authcode_sdk-1.0.whl 
-rw-rw-r-- 1 daniel daniel 4,8K nov 22 14:08 /home/daniel/Downloads/ups_oauth_authcode_sdk-1.0.whl
$ pip install ~/Downloads/ups_oauth_authcode_sdk-1.0.whl 
ERROR: ups_oauth_authcode_sdk-1.0.whl is not a valid wheel filename.
$ pip install ~/Downloads/ups_oauth_authcode_sdk
ERROR: Invalid requirement: '/home/daniel/Downloads/ups_oauth_authcode_sdk': Expected package name at the start of dependency specifier
    /home/daniel/Downloads/ups_oauth_authcode_sdk
    ^
Hint: It looks like a path. File '/home/daniel/Downloads/ups_oauth_authcode_sdk' does not exist.
```

I'm on Ubuntu 22 using python 3.9.20 (inside a virtual env), pip 24.3.1 and setuptools 75.6.0.
(I get the same errors for `ups_oauth_client_credential_sdk-1.0.whl`)

**Comment by HarrisonAlmeida** [comment]
> I'm having the same problem:
> 
> ```
> $ ls -lah ~/Downloads/ups_oauth_authcode_sdk-1.0.whl 
> -rw-rw-r-- 1 daniel daniel 4,8K nov 22 14:08 /home/daniel/Downloads/ups_oauth_authcode_sdk-1.0.whl
> $ pip install ~/Downloads/ups_oauth_authcode_sdk-1.0.whl 
> ERROR: ups_oauth_authcode_sdk-1.0.whl is not a valid wheel filename.
> $ pip install ~/Downloads/ups_oauth_authcode_sdk
> ERROR: Invalid requirement: '/home/daniel/Downloads/ups_oauth_authcode_sdk': Expected package name at the start of dependency specifier
>     /home/daniel/Downloads/ups_oauth_authcode_sdk
>     ^
> Hint: It looks like a path. File '/home/daniel/Downloads/ups_oauth_authcode_sdk' does not exist.
> ```
> 
> I'm on Ubuntu 22 using python 3.9.20 (inside a virtual env), pip 24.3.1 and setuptools 75.6.0. (I get the same errors for `ups_oauth_client_credential_sdk-1.0.whl`)

I was able to solve it by adding `-cp39-cp39m-win_amd64` to the filename. It's related to python version and compatibility info, I believe. 
I'm using `poetry` though, so that's working for me:
`ups_oauth_client_credential_sdk = {file = "./ups_oauth_client_credential_sdk-1.0-cp39-cp39m-win_amd64.whl"}` 

Also needed to add the `./` at the start of the filepath

**Comment by UPSMichael** [comment]
Hi Daniel, the output from pip suggests there may be an issue with the file path used. Can you ensure the file exists in that location and that the path is correct? You mentioned that you're using a virtual environment, so it's possible that the path used may need to be modified.

**Comment by daniel-gomes** [comment]
> Hi Daniel, the output from pip suggests there may be an issue with the file path used. Can you ensure the file exists in that location and that the path is correct? You mentioned that you're using a virtual environment, so it's possible that the path used may need to be modified.

@UPSMichael  I did ensure that the file existed, as the `ls -lah ~/Downloads/ups_oauth_authcode_sdk-1.0.whl` command output on my previous post shows.

> I was able to solve it by adding -cp39-cp39m-win_amd64 to the filename. It's related to python version and compatibility info, I believe.

@HarrisonAlmeida that was indeed the rifght direction: after investigating a bit, I managed to install it by renaming e.g. the `ups_oauth_authcode_sdk-1.0.whl` file to `ups_oauth_authcode_sdk-1.0-py3-none-any.whl`. 

@UPSMichael it's probably a good idea to update the documentation to mention this fact? Or even renaming the file in the repo (although I'm not sure that is valid for all scenarios)

**Comment by UPSMichael** [comment]
Thank you for the feedback and suggestion. I'll bring it up with the rest of the team and we'll discuss possible solutions or changes that can be made to make this easier and more clear.
