### ISSUE TITLE
.NET NUGET Packages do not appear to be published and/or public

### ISSUE THREAD

**Issue by jbrown29** [UPS-API/UPS-SDKs#4]
.NET NUGET Packages do not appear to be published and/or public

**Comment by jbrown29** [comment]
@UPSMichael, Is there something I might be missing here? I cannot find this on NUGET.org. I've contacted UPS help desk about this, but wanted to reach out directly here.

**Comment by UPSMichael** [comment]
Hi @jbrown29 , thanks for reaching out. These packages are not published at nuget.org, but rather they are located here at GitHub. In order for the command to add the package to your project to work you will first need to add GitHub packages as a source. [Here](https://github.com/UPS-API/UPS-SDKs/issues/4) is a link to some information from GitHub about doing this. By default, .Net uses nuget.org to fetch any nuget packages you install. This should fix your issue.

**Comment by jbrown29** [comment]
> Hi @jbrown29 , thanks for reaching out. These packages are not published at nuget.org, but rather they are located here at GitHub. In order for the command to add the package to your project to work you will first need to add GitHub packages as a source. [Here](https://github.com/UPS-API/UPS-SDKs/issues/4) is a link to some information from GitHub about doing this. By default, .Net uses nuget.org to fetch any nuget packages you install. This should fix your issue.

your "here" link is broken

**Comment by UPSMichael** [comment]
Hmmm, I'll edit it for future views, but here's the link.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
