### ISSUE TITLE
Structure of PHP project is not the best fit for composer

### ISSUE THREAD

**Issue by ataypamart** [UPS-API/UPS-SDKs#5]
Hey,

the structure of the PHP SDK is not very friendly with what i beleive to be the most common PHP package manager, ie composer. See https://github.com/composer/packagist/issues/472 for painful details (thread has been active over 9 years, amazing!)

The issue here is that while there is one repo per language, there are two subfolders each with composer.json files, one for each oauth flow. This structrue cannot be addressed directly as a composer dependency.

In this particular context, and since you already pay the price of having one repo per language, i guess there are other solutions: have both oauth flows in the same package structure, or, more complex i suppose, having two repos, one per flow.

Thanks
Adrien

**Comment by UPSMichael** [comment]
Hi Adrien, thank you for bringing this up. Unfortunately, we don't have any plans to migrate both flows into a single package structure. I understand that it's cumbersome to deal with. Even though it may be less ideal, the source files for both Auth Code and Client Credentials are available to use and could be included in your own project.

**Comment by ataypamart** [comment]
Ok no worries, I know how to resolve this "manually" but since you use the word SDK for this stuff, the DX sort of matters (ie clients are the developers there ;) The current structure kills dead the no-friction "just add this line to your composer.json file" if i am not mistaken

**Comment by torro-uk** [comment]
> Ok no worries, I know how to resolve this "manually" but since you use the word SDK for this stuff, the DX sort of matters (ie clients are the developers there ;) The current structure kills dead the no-friction "just add this line to your composer.json file" if i am not mistaken

Hi! Can you please provide any additional insights or how i can use composer to install the PHP code. Trying the standard "composer require" doesn't work for obvious reasons. I'd rather not manually download and include the files in my project as that kinds defeats the point. Any advice would be appreciated!
